import mongoose from "mongoose";
const pickupSchema = new mongoose.Schema(
  {
    name: String,
    phone: String,
    address: { type: String, required: true },
    material: { type: String, required: true },
    weightKg: Number,
    description: { type: String, trim: true, maxlength: 500 },
    imageUrl: String,
    status: {
      type: String,
      enum: ["requested", "assigned", "collected", "verified"],
      default: "requested",
    },
    scheduledFor: Date,
    serviceType: { type: String, default: "scrap_pickup" },
    pickupMode: { type: String, enum: ["household", "business", "industrial"], default: "household" },
    recurring: { type: String, enum: ["once", "weekly", "monthly"], default: "once" },
    userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    assignedCollector: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    paymentMethod: { type: String, enum: ["cash", "upi"], default: "cash" },
    paymentStatus: {
      type: String,
      enum: ["pending", "paid"],
      default: "pending",
    },
    estimatedAmount: Number,
    pricePerKg: Number,
    weighedKg: Number,
    weightSource: { type: String, enum: ["digital", "iot"] },
    verificationCode: String,
    verificationStatus: { type: String, enum: ["pending", "verified"], default: "pending" },
    verifiedAt: Date,
    couponCode: String,
    couponBonus: { type: Number, default: 0 },
    invoiceNumber: String,
    inventoryListed: { type: Boolean, default: false },
    lat: Number,
    lng: Number,
    statusHistory: [
      {
        status: String,
        at: { type: Date, default: Date.now },
        by: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
      },
    ],
  },
  { timestamps: true },
);
export const Pickup = mongoose.model("Pickup", pickupSchema);
